fix: http methods
TheRealKasumi/TesLight pull request #154
Opened 2023-03-05 16:56 UTC by TheRealKasumi

As discussed it would probably be "more correct" to use `patch` instead of `post` at some points. So let's do it, should be easy.

2023-03-05 17:45 UTC, JakobLichterfeld requested changes
lgtm beside one line, see in-line comment

2023-03-05 17:45 UTC, JakobLichterfeld commented on documentation/api/TesLight API.postman_collection.json
> +									"src": "/C:/Users/Kasumi/Desktop/xl/all_the_things_she_said.fseq"
I don't get this insider 😅

2023-03-06 14:58 UTC, TheRealKasumi commented on documentation/api/TesLight API.postman_collection.json
> +									"src": "/C:/Users/Kasumi/Desktop/xl/all_the_things_she_said.fseq"
Oooopsi xD

2023-03-07 11:08 UTC, JakobLichterfeld submitted a review, later dismissed
lgtm

2023-03-19 08:55 UTC, danielbayerlein commented
@TheRealKasumi I've changed the HTTP request methods in the UI.

2023-03-19 11:41 UTC, danielbayerlein submitted a review, later dismissed

2023-03-19 11:54 UTC, TheRealKasumi commented
Works for me when you are sure the methods are correct😋. I can't really test it right now. But in case of problems we can do a quick fix I guess.

2023-03-26 15:53 UTC, TheRealKasumi commented
Seems to be all working. Maybe a small adjustment is required after https://github.com/TheRealKasumi/TesLight/pull/172.

2023-03-28 05:42 UTC, TheRealKasumi reviewed
Thanks! From my side we can merge.

2023-03-31 08:14 UTC, danielbayerlein approved these changes

2023-03-31 08:14 UTC, merged